name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn lint

      - name: Check types
        run: yarn tsc
